#!/bin/sh
REDIS_HOST=${REDIS_HOST:-localhost}
sed -i "s/pushover_app_token/$PUSHOVER_APP_TOKEN/" beehive.conf
sed -i "s/pushover_user_token/$PUSHOVER_USER_TOKEN/" beehive.conf
sed -i "s/redis_host/$REDIS_HOST/" beehive.conf
beeydl poll > beeydl.log 2>&1 &
./beehive --bind 0.0.0.0:8181 
