version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - beeydl
  caddy:
    image: abiosoft/caddy:1.0.3-no-stats
    hostname: caddy
    restart: always
    ports:
     - 2015:2015
    networks:
     - beeydl
    volumes:
     - ./caddy/Caddyfile:/etc/Caddyfile
     - ./caddy/config:/root/.caddy
    environment:
     - ACME_AGREE=true
  minio:
    image: minio/minio
    hostname: minio
    restart: always
    networks:
     - beeydl
    volumes:
     - ./buckets:/buckets
    command: server /buckets
    environment:
     - MINIO_ACCESS_KEY=test123
     - MINIO_SECRET_KEY=secret123
  beehive:
    image: beeydl
    hostname: beehive
    restart: always
    ports:
     - 8181:8181
     - 12345:12345
    networks:
     - beeydl
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - PUSHOVER_USER_TOKEN=${PUSHOVER_USER_TOKEN}
     - PUSHOVER_APP_TOKEN=${PUSHOVER_APP_TOKEN}
    volumes:
     - ./buckets/ydl-video:/root/video
     - ./config:/root/config
  redis:
    hostname: redis
    image: redis
    restart: always
    networks:
     - beeydl

networks:
  beeydl:
    driver: bridge
